shop_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'


urlpatterns = [
  path('', views.index, name='index'),
  path('products/<int:product_id>/', views.product, name='product'),
  path('clients/', views.clients, name='clients'),
  path('clients/<int:client_id>/', views.client, name='client'),
  path('maillots/', views.maillots, name='maillots'),
  path('maillots/<int:maillot_id>/', views.maillot, name='maillot'),
  path('products/<int:product_id>/comment_form', views.comment_form, name='comment_form')
  
]

shop_project/shop_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'


urlpatterns = [
  path('', views.index, name='index'),
  path('products/<int:product_id>/', views.product, name='product'),
  path('clients/', views.clients, name='clients'),
  path('clients/<int:client_id>/', views.client, name='client'),
  path('maillots/', views.maillots, name='maillots'),
  path('maillots/<int:maillot_id>/', views.maillot, name='maillot'),
  path('products/<int:product_id>/comment_form', views.comment_form, name='comment_form'),
  path('products/<int:product_id>/question_form', views.question_form, name='question_form'),
  path('questions/<int:question_id>/responseform', views.responseform, name='responseform'),
  path('comments/<int:comment_id>/commentresponseform', views.commentresponseform, name='commentresponseform'),

  
]

shop_project/shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop_app import views
from contact_app import views
from profile_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop_app/', include('shop_app.urls')),
    path('contact_app/', include('contact_app.urls')),
    path('profile_app/', include('profile_app.urls')),

]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop_app import views
from contact_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop_app/', include('shop_app.urls')),
    path('contact_app/', include('contact_app.urls')),

]

shop_app/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=264)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(default="static/images/ecran.png", upload_to='static/images/' )

    def __str__(self):
        return (self.name)

    # def __repr__(self):
    #     return "<Product {}>".format(self.name)



class Client(models.Model):
	first_name = models.CharField(max_length=264)
	last_name = models.CharField(max_length=264)
	password = models.CharField(max_length=50)
	email = models.EmailField()
	profil_picture = models.ImageField(default="static/images/profil_pictures/defaultpicture.jpg", upload_to='static/images/profil_pictures/' )



	def __str__(self):
		return self.first_name

	def __repr__(self):
		return "<Client {}>".format(self.email)

class Maillot(models.Model):
	name = models.CharField(max_length=264)
	description = models.TextField()
	price = models.DecimalField(max_digits=5, decimal_places=2)
	maillot_picture = models.ImageField(default="static/images/maillots_pictures/maillotdefaut.jpg", upload_to='static/images/maillots_pictures/' )


	def __str__(self):
		return self.name

	
	def __repr__(self):
		return "<Client {}>".format(self.name)

class Comment(models.Model):
	username = models.CharField(max_length=264)
	text = models.TextField()
	date = models.DateField()
	product = models.ForeignKey(Product , on_delete=models.CASCADE)


	def __str__(self):
		return self.username

	
	def __repr__(self):
		return "<Client {}>".format(self.username)


		


# class ImageField(upload_to=None, height_field=None, width_field=None, max_length=100 **options)

shop_project/shop_app/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=264)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(default="static/images/ecran.png", upload_to='static/images/' )

    def __str__(self):
        return (self.name)

    # def __repr__(self):
    #     return "<Product {}>".format(self.name)



class Client(models.Model):
	first_name = models.CharField(max_length=264)
	last_name = models.CharField(max_length=264)
	password = models.CharField(max_length=50)
	email = models.EmailField()
	profil_picture = models.ImageField(default="static/images/profil_pictures/defaultpicture.jpg", upload_to='static/images/profil_pictures/' )



	def __str__(self):
		return self.first_name

	def __repr__(self):
		return "<Client {}>".format(self.email)

class Maillot(models.Model):
	name = models.CharField(max_length=264)
	description = models.TextField()
	price = models.DecimalField(max_digits=5, decimal_places=2)
	maillot_picture = models.ImageField(default="static/images/maillots_pictures/maillotdefaut.jpg", upload_to='static/images/maillots_pictures/' )


	def __str__(self):
		return self.name

	
	def __repr__(self):
		return "<Client {}>".format(self.name)

class Comment(models.Model):
	username = models.CharField(max_length=264)
	text = models.TextField()
	date = models.DateField()
	product = models.ForeignKey(Product , on_delete=models.CASCADE)


	def __str__(self):
		return self.username

	
	def __repr__(self):
		return "<Client {}>".format(self.username)


class Question(models.Model):
	username = models.CharField(max_length=264)
	title = models.CharField(max_length=264)
	text = models.TextField()
	product = models.ForeignKey(Product , on_delete=models.CASCADE)

	def __str__(self):
		return self.username

	def __repr__(self):
		return "<Client {}>".format(self.text)	

			
class Response(models.Model):
	username = models.CharField(max_length=264)
	text = models.TextField()
	question = models.ForeignKey(Question , on_delete=models.CASCADE)

	def __str__(self):
		return self.username

	def __repr__(self):
		return "<Client {}>".format(self.text)

class CommentResponse(models.Model):
	username = models.CharField(max_length=264)
	text = models.TextField()
	comment = models.ForeignKey(Comment , on_delete=models.CASCADE)	

	def __str__(self):
		return self.username

	def __repr__(self):
		return "<Client {}>".format(self.text)	

# class ImageField(upload_to=None, height_field=None, width_field=None, max_length=100 **options)

shop_app/forms.py
from django import forms
from shop_app.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['username','text']
		widgets = {
		'username':forms.TextInput(attrs={
			'id':'comment-username',
			'placeholder':'username',
			'required':True
			}),
		'text':forms.Textarea(attrs={
			'id':'comment-text',
			'placeholder':'Write a comment here ...',
			'required':True
			}),
		}

	

shop_project/shop_app/forms.py
from django import forms
from shop_app.models import Comment, Question,Response, CommentResponse

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['username','text']
		widgets = {
		'username':forms.TextInput(attrs={
			'id':'comment-username',
			'placeholder':'username',
			'required':True
			}),
		'text':forms.Textarea(attrs={
			'id':'comment-text',
			'placeholder':'Write a comment here ...',
			'required':True
			}),
		}

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['username','title','text']
		widgets = {
		'username':forms.TextInput(attrs={
			'id':'question-username',
			'placeholder':'username',
			'required':True
			}),
		'title':forms.TextInput(attrs={
			'id':'question-title',
			'placeholder':'title',
			'required':True
			}),
		'text':forms.Textarea(attrs={
			'id':'question-text',
			'placeholder':'Write a question here ...',
			'required':True
			}),
		}
class ResponseForm(forms.ModelForm):
	class Meta:
		model = Response
		fields = ['username','text']
		widgets = {
		'username':forms.TextInput(attrs={
			'id':'response-username',
			'placeholder':'username',
			'required':True
			}),
		'text':forms.Textarea(attrs={
			'id':'response-text',
			'placeholder':'Write a response here ...',
			'required':True
			}),
		}


class CommentResponseForm(forms.ModelForm):
	class Meta:
		model = CommentResponse
		fields = ['username','text']
		widgets = {
		'username':forms.TextInput(attrs={
			'id':'commentresponse-username',
			'placeholder':'username',
			'required':True
			}),
		'text':forms.Textarea(attrs={
			'id':'commentresponse-text',
			'placeholder':'Write a response to the comment here ...',
			'required':True
			}),
		}

shop_app/views.py
from django.shortcuts import render
from shop_app.models import Product , Client, Maillot, Comment
from shop_app.forms import CommentForm
import datetime 

# Create your views here.
def index(request):
   products = Product.objects.all()[:20]
   return render(request,"index.html",context={'products':products})
def product(request,product_id):
	product = Product.objects.get(id=product_id)
	comments = Comment.objects.all().filter(product_id=product.id)
	return render(request,"product.html",context={'product': product, 'comments':comments })

def clients(request):
	clients = Client.objects.all()[:20]
	return render(request, "clients.html", context={'clients': clients })

def client(request, client_id):
	client = Client.objects.get(id=client_id)
	return render(request, "client.html", context={'client': client })

def maillots(request):
	maillots = Maillot.objects.all()
	return render(request, "maillots.html", context={'maillots': maillots })

def maillot(request, maillot_id):
	maillot = Maillot.objects.get(id=maillot_id)
	return render(request, "maillot.html", context={'maillot': maillot })

def comment_form(request, product_id):
	if request.method == 'POST':
		username = request.POST.get('username')
		text = request.POST.get('text')
		product = Product.objects.get(id=product_id)
		date = datetime.datetime.now()
		Comment.objects.get_or_create(username=username,text=text,date=date,product=product)
	

	
	comment_form = CommentForm()
	return render(request, "comment_form.html", context={'comment_form': comment_form })

shop_project/shop_app/views.py
from django.shortcuts import render ,redirect
from shop_app.models import Product , Client, Maillot, Comment, Question, Response, CommentResponse
from shop_app.forms import CommentForm, QuestionForm, ResponseForm, CommentResponseForm
import datetime 

# Create your views here.
def index(request):
   products = Product.objects.all()[:20]
   return render(request,"index.html",context={'products':products})

def product(request, product_id):
  product = Product.objects.get(id=product_id)
  comments = Comment.objects.all().filter(product_id=product_id)

  comments_with_responses = []
  for comment in comments:
    comment_with_responses = {
      'comment': comment,
      'commentresponses': CommentResponse.objects.all().filter(comment_id=comment.id)
    }

    comments_with_responses.append(comment_with_responses)



  questions = Question.objects.all().filter(product_id=product_id)

  questions_with_responses = []
  for question in questions:
    question_with_responses = {
      'question': question,
      'responses': Response.objects.all().filter(question_id=question.id)
    }

    questions_with_responses.append(question_with_responses)

  return render(request, 'product.html', context={
      'product': product,
      'questions': questions_with_responses,
      'comments': comments_with_responses,
    })

def clients(request):
	clients = Client.objects.all()[:20]
	return render(request, "clients.html", context={'clients': clients })

def client(request, client_id):
	client = Client.objects.get(id=client_id)
	return render(request, "client.html", context={'client': client })

def maillots(request):
	maillots = Maillot.objects.all()
	return render(request, "maillots.html", context={'maillots': maillots })

def maillot(request, maillot_id):
	maillot = Maillot.objects.get(id=maillot_id)
	return render(request, "maillot.html", context={'maillot': maillot })

def comment_form(request, product_id):
	if request.method == 'POST':
		username = request.POST.get('username')
		text = request.POST.get('text')
		product = Product.objects.get(id=product_id)
		date = datetime.datetime.now()
		Comment.objects.get_or_create(username=username,text=text,date=date,product=product)
	

	
	comment_form = CommentForm()
	return render(request, "comment_form.html", context={'comment_form': comment_form })



def question_form(request, product_id):
	if request.method == 'POST':
		username = request.POST.get('username')
		title = request.POST.get('title')
		text = request.POST.get('text')
		product = Product.objects.get(id=product_id)
		Question.objects.get_or_create(username= username,title=title,text=text,product=product)

		return redirect('/shop_app/products/{}/'.format(product_id))


	return render(request, "question_form.html", context={'question_form': QuestionForm()})


def responseform(request, question_id):
	if request.method == 'POST':
		username = request.POST.get('username')
		text = request.POST.get('text')
		question = Question.objects.get(id=question_id)
		Response.objects.get_or_create(username= username,text=text,question=question)

		return redirect('/shop_app/products/{}/'.format(question.product.id))


	return render(request, "responseform.html", context={'responseform': ResponseForm()})


def commentresponseform(request, comment_id):
	if request.method == 'POST':
		username = request.POST.get('username')
		text = request.POST.get('text')
		comment = Comment.objects.get(id=comment_id)
		CommentResponse.objects.get_or_create(username= username,text=text,comment=comment)

		return redirect('/shop_app/products/{}/'.format(comment.product.id))


	return render(request, "commentresponseform.html", context={'commentresponseform': CommentResponseForm()})

shop_project/shop_app/templates/commentresponseform.html
 <!DOCTYPE html>
 <html>
 <head>
 	<title>send a response</title>
 </head>
 <body>
 	<h1> Ajouter une reponse</h1>
<form action="commentresponseform" method="POST">
  {{commentresponseform.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="send a response">
 
 </body>
 </html>

shop_project/shop_app/templates/product.html
<!DOCTYPE html>
<html>
<head>{% load staticfiles %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{{ product.name }}</title>
  <meta charset="utf-8">
</head>
<body>

  <div class="container">
    <nav class="navbar navbar-light bg-secondary">
      <a class="navbar-brand text-light" href="/">
        <i class="fab fa-spotify"></i> 
        Foot Locker
      </a>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light my-2 my-sm-0 text-light" type="submit">Search</button>
      </form>
    </nav>
    
    <div class="row mt-2 ml-1">
      <h1 class="product-name">{{ product.name }}</h1>
    </div>
    
    <div class="row">  
      <div class="col-sm ">
        <img class="img-thumbnail" src="http://{{ request.get_host}}/{{ product.image }}">
      </div>
      

      <div class="col-sm">
        <h4>Product details</h4>
        <ul class="#">
         
          <li>{{ product.description }}</li>
          
        </ul>
      </div>

      <div class="col-sm">
        
        <p class="mt-5">{{ product.description }}</p>
        <h2 class="mb-5">${{ product.price }}</h2>
        <button type="button" class="btn btn-lg btn-warning w-100 text-light " disabled>
          <i class="fas fa-shopping-cart "></i>
          Buy Now
        </button>  
        <ul class="mt-5">
          <h1>question</h1>
          {% for question in questions %}
          <li class="list-unstyled">
           <!--  <img class="rounded-circle w-50" src="http://{{ request.get_host}}/{{ comment.user_picture }}"> -->
            <h4>{{ question.question.username }} -- {{ question.question.title }}</h4>
           <p>{{ question.question.text }}</p> 

          </li>
          <li class="list-unstyled">
           <!--  <img class="rounded-circle w-50" src="http://{{ request.get_host}}/{{ comment.user_picture }}"> -->
           <h2>response</h2>
           {% for response in question.responses %}
            <h4>{{ response.username }} -- {{ response.text}}</h4>
           <p>{{ response.text }}</p> 
           <a href="{% url 'shop_app:responseform' question.question.id %}"class="btn btn-outline-primary btn-block">write a response</a> 
          </li>

          {% endfor %}
          {% endfor %}</ul>
        </ul>

        <ul class="mt-5">
          <h1>Commentaires</h1>
          {% for comment in comments %}
          <li class="list-unstyled">
           <!--  <img class="rounded-circle w-50" src="http://{{ request.get_host}}/{{ comment.user_picture }}"> -->
            <h4>{{ comment.comment.username }} --{{ comment.comment.date }}</h4>
            <p>{{ comment.comment.text }}</p>
          </li>
          <li><h2>response of the comment</h2>
           {% for response in comment.commentresponses %}
            <h4>{{ response.username }} -- {{ response.text}}</h4>
           <p>{{ response.text }}</p> 
           <a href="{% url 'shop_app:commentresponseform' comment.comment.id %}" class="btn btn-outline-primary btn-block">write a response</a> 

          </li>

          {% endfor %}
          {% endfor %}
        </ul>
      </div>
     
  </div>

</body>
</html>

shop_project/shop_app/templates/question_form.html
 <!DOCTYPE html>
 <html>
 <head>
 	<title>send a question</title>
 </head>
 <body>
 	<h1> Ajouter une question</h1>
<form action="question_form" method="POST">
  {{question_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="send a question">
    </div>
 
 </body>
 </html>

shop_project/shop_app/templates/responseform.html
 <!DOCTYPE html>
 <html>
 <head>
 	<title>send a response</title>
 </head>
 <body>
 	<h1> Ajouter une reponse</h1>
<form action="response_form" method="POST">
  {{responseform.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="send a response">
 
 </body>
 </html>